name = "Integrated AI Voice Control System"
author = "Asaayu"
prefix = "ivcs"
mainprefix = "z"

[version]
major = 1
minor = 1
patch = 0
build = 0

[files]
include = [
    "grammar/**/*",
    "*.dll",
    "*.so",
    "LICENSE",
]
exclude = [
    "**/*.psd"
]