name = "Integrated AI Voice Control System"
author = "Asaayu"
prefix = "ivcs"
mainprefix = "z"

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

[version]
major = 2
minor = 0
patch = 6
build = 69

[files]
include = [
    "grammar/*.pls",
    "grammar/*.xml",
    "version_check.txt",
    "*.dll",
    "LICENSE",
]
exclude = [
    "**/*.psd",
    "**/*.png",
]