name: Ensure Extension Builds on Changes

on:
  push:
    branches:
      - dev
    paths:
      - "extension/**"
      - "grammar/**"
      - ".github/workflows/dev-ensure-extension-builds.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step: Cache NuGet packages
      - name: Cache NuGet packages
        id: cache-nuget
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.nuget\packages
          key: nuget-${{ runner.os }}-${{ hashFiles('extension/IntegratedVoiceControlSystem.sln') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Step: Install NuGet packages
      - name: Install NuGet packages
        run: nuget restore extension/IntegratedVoiceControlSystem.sln

      # Step: Install Microsoft Build Tools 2015 (only if not cached)
      - name: Install Microsoft Build Tools 2015
        run: |
          Write-Host "Downloading Microsoft Build Tools 2015..."
          $buildToolsUrl = "https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe"
          Invoke-WebRequest -Uri $buildToolsUrl -OutFile "BuildTools_Full.exe"
          Start-Process -FilePath "./BuildTools_Full.exe" -ArgumentList "/quiet /norestart" -NoNewWindow -Wait
          Remove-Item -Path "./BuildTools_Full.exe" -Force

      # Step: Build x64 Extension Configuration
      - name: Build x64 Extension Configuration
        run: msbuild extension/IntegratedVoiceControlSystem.sln /p:Configuration=Release /p:Platform=x64

      # Step: Build x86 Extension Configuration
      - name: Build x86 Extension Configuration
        run: msbuild extension/IntegratedVoiceControlSystem.sln /p:Configuration=Release /p:Platform=x86
